services: 
  django-client: 
    container_name: client
    build: . 

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
  api: 
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db